### ISSUE TITLE
Server returns no response when logout with no token

### ISSUE THREAD

**Issue by STommydx** [huantingwei/comp4111project#10]
**Describe the bug**
Server returns no response when logout with no token.

**To Reproduce**
1. Logout with no token
`GET /BookManagementService/logout`

**Expected behavior**
`400 Bad Request`

**What actually happens**
The server return no response with the following NPE thrown in console
```
Exception in thread "Thread-1" java.lang.NullPointerException
	at comp4111project.Handlers.NLogoutRequestHandler.getTokenFromURI(NLogoutRequestHandler.java:93)
	at comp4111project.Handlers.NLogoutRequestHandler.handleInternal(NLogoutRequestHandler.java:61)
	at comp4111project.Handlers.NLogoutRequestHandler$1.run(NLogoutRequestHandler.java:41)
```

**Comment by huantingwei** [comment]
Bug is confirmed, thanks.
