### ISSUE TITLE
[PUT /transaction] API does not handle bad/missing properties correctly

### ISSUE THREAD

**Issue by Derppening** [huantingwei/comp4111project#15]
### Issue description

Same as #14, but this time for `PUT /transaction`

### Steps to reproduce the issue

Assuming the database and web server is running:

1.  Login using a valid token.
2. Submit a `POST /transaction` request without a payload.
3. Submit a PUT /transaction request with at least one of Book or Action properties' value being null or missing.

### What's the expected result?

- The API returns `400 Bad Request`

### What's the actual result?

- The client receives no response from the server

```
curl -v -X PUT --data "{}" http://localhost:8081/BookManagementService/transaction\?token\=dXNlcjAwMDAx                                     
*   Trying ::1:8081...
* connect to ::1 port 8081 failed: Connection refused
*   Trying 127.0.0.1:8081...
* Connected to localhost (127.0.0.1) port 8081 (#0)
> PUT /BookManagementService/transaction?token=dXNlcjAwMDAx HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.70.0
> Accept: */*
> Content-Length: 2
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 2 out of 2 bytes
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

- The server throws a `NullPointerException`

```
Exception in thread "Thread-6" java.lang.NullPointerException
        at comp4111project.Handlers.NTransactionRequestHandler.handleInternal(NTransactionRequestHandler.java:167)
        at comp4111project.Handlers.NTransactionRequestHandler.access$000(NTransactionRequestHandler.java:33)
        at comp4111project.Handlers.NTransactionRequestHandler$1.run(NTransactionRequestHandler.java:56)
```

(The stacktrace is slightly different depending on which field is missing or `null`)

**Comment by huantingwei** [comment]
Bug is confirmed, thanks.
