### ISSUE TITLE
Server returns no response when looking up books with non-numeric limit

### ISSUE THREAD

**Issue by STommydx** [huantingwei/comp4111project#6]
**Describe the bug**
Server returns no response when looking up books with non-numeric limit.

**To Reproduce**
1. Login as usual
2. Add the following book
```json
{
	"Title": "Alice in Wonderland",
	"Author": "Lewis Carroll",
	"Publisher": "Macmillan Publishers",
	"Year": 1865
}
```
3. Search book with limit `abc`.
`GET BookManagementService/books?limit=abc&token={{token}}`

**Expected behavior**
`400 Bad Request` or other custom behavior that does not crash the server.

**What actually happens**
The server return no response with the following error thrown in console
```
Exception in thread "Thread-12" java.lang.NumberFormatException: For input string: "abc"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at comp4111project.Handlers.NAddLookUpBookRequestHandler.handleInternal(NAddLookUpBookRequestHandler.java:151)
	at comp4111project.Handlers.NAddLookUpBookRequestHandler$1.run(NAddLookUpBookRequestHandler.java:59)
```

**Comment by chanhyeok95** [comment]
Dear @STommydx 

Bug is confirmed, thanks.
