### ISSUE TITLE
Server returns no response when login with integer password

### ISSUE THREAD

**Issue by STommydx** [huantingwei/comp4111project#9]
**Describe the bug**
Server returns no response when login with integer password.

**To Reproduce**
1. Login with the following payload
```json
{
	"Username": "user00001",
	"Password": 0
}
```

**Expected behavior**
`400 Bad Request`

**What actually happens**
The server return no response with the following error thrown in console
```
Exception in thread "Thread-72" java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at comp4111project.QueryManager.loginUser(QueryManager.java:482)
	at comp4111project.Handlers.NLoginRequestHandler.handleInternal(NLoginRequestHandler.java:93)
	at comp4111project.Handlers.NLoginRequestHandler$1.run(NLoginRequestHandler.java:55)
```

**Comment by huantingwei** [comment]
Bug is confirmed, thanks.
